version: "2"

services:
  app:
    container_name: hp_api
    build: .
    command: yarn dev
    volumes:
      - .:/app/
      - node_modules:/app/node_modules
    ports:
      - "3013:3013"
    depends_on:
      - db
    links:
      - db
    networks:
      - default
      - proxy
    env_file: .env
  db:
    container_name: hp_db
    image: postgres:9.6.5-alpine
    volumes:
       - db-data:/var/lib/postgresql
    ports:
      - "5432"
    env_file: .env
    environment:
      PGHOST: localhost

networks:
  proxy:

volumes:
  node_modules:
  db-data:
